version: '2.4'

services:

  web:
    image: nginx:1.20-alpine
    container_name: web
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./docker/supervisord/supervisord.conf:/etc/supervisord.conf:cached
      - ./services:/var/www:cached
      - ./logs:/logs:cached
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www

  php:
    build: ./docker/php/7.4/
    container_name: php
    restart: always
    logging:
      driver: none
    volumes_from:
      - web
    working_dir: /var/www

  php-worker:
    build: ./docker/php/7.4/
    container_name: php-worker
    restart: always
    logging:
      driver: none
    volumes_from:
      - web
    working_dir: /var/www
    entrypoint: ["/usr/bin/supervisord", "-n"]

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    logging:
      driver: none
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  mysql:
    image: mariadb:10.5
    container_name: mysql
    restart: always
    logging:
      driver: none
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    command: mysqld --sql_mode=''

  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always
    logging:
      driver: none
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  mysql-data:
  redis-data:
    