version: '2.4'

services:

  web:
    image: doanbaanh/nginx:1.20
    container_name: web
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./workspace:/var/www:cached
      - ./logs:/logs:cached
    ports:
      - 80:80
      - 443:443

  php:
    image: doanbaanh/php-fpm:7.4
    # image: doanbaanh/php-fpm:7.4-xdebug
    container_name: php
    restart: always
    logging:
      driver: none
    volumes_from:
      - web
    working_dir: /var/www
    user: "${UID}:${GID}"

  php-worker:
    image: doanbaanh/php-fpm:7.4
    container_name: php-worker
    restart: always
    logging:
      driver: none
    volumes_from:
      - web
    entrypoint: ["/usr/bin/supervisord", "-n"]
    user: "${UID}:${GID}"

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    logging:
      driver: none
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret

  mysql:
    image: mariadb:10.5
    container_name: mysql
    restart: always
    logging:
      driver: none
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command: mysqld --sql_mode=''

  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always
    logging:
      driver: none
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  mysql-data:
  redis-data:
