version: '2.4'

services:

  web:
    image: nginx:1.20-alpine
    container_name: web
    restart: always
    volumes:
      - ./certificates/letsencrypt:/etc/letsencrypt:cached
      - ./certificates/lib:/var/lib/letsencrypt:cached
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/supervisord.conf:/etc/supervisord.conf:ro
      - ./services:/var/www:cached
      - ./logs:/logs:cached
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes_from:
      - web
    command: certonly --webroot --webroot-path=/var/www --email doanbaanh@gmail.com --agree-tos --no-eff-email --staging -d sify.ru -d www.sify.ru

  php:
    image: doanbaanh/php-fpm
    # build: ./docker/php/7.4-xdebug
    container_name: php
    restart: always
    logging:
      driver: none
    volumes_from:
      - web
    working_dir: /var/www
    user: "${UID}:${GID}"

  php-worker:
    image: doanbaanh/php-fpm
    container_name: php-worker
    restart: always
    logging:
      driver: none
    volumes_from:
      - web
    working_dir: /var/www
    entrypoint: ["/usr/bin/supervisord", "-n"]
    user: "${UID}:${GID}"

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    logging:
      driver: none
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret

  mysql:
    image: mariadb:10.5
    container_name: mysql
    restart: always
    logging:
      driver: none
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command: mysqld --sql_mode=''

  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always
    logging:
      driver: none
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  mysql-data:
  redis-data:
