version: '2.4'

services:

  web:
    image: nginx:${NGINX_VERSION}-alpine
    container_name: web
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./workspace:/var/www:cached
      - ./logs:/logs:cached
    ports:
      - 80:80
      - 443:443

  php:
    # build: ./php-fpm
    image: doanbaanh/php-fpm
    container_name: php
    restart: always
    logging:
      driver: none
    volumes_from:
      - web
    working_dir: /var/www
    user: "${UID}:${GID}"

  php-worker:
    image: doanbaanh/php-fpm
    container_name: php-worker
    restart: always
    logging:
      driver: none
    volumes_from:
      - web
    volumes:
      - ./php-worker/supervisord.conf:/etc/supervisord.conf:ro
    entrypoint: ["/usr/bin/supervisord", "-n"]
    user: "${UID}:${GID}"

  postgres:
    image: postgres:${POSTGRES_VERSION}-alpine
    container_name: postgres
    restart: always
    logging:
      driver: none
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret

  mysql:
    image: mariadb:${MARIADB_VERSION}
    container_name: mysql
    restart: always
    logging:
      driver: none
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command: mysqld --sql_mode=''

  redis:
    image: redis:${REDIS_VERSION}-alpine
    container_name: redis
    restart: always
    logging:
      driver: none
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  mysql-data:
  redis-data:

networks:
  default:
    internal: true
    name: web
