version: '2.4'

services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 9000:9000

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 9001:8080

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 9002:8081
    depends_on:
      - redis

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 9003:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: null
      ME_CONFIG_MONGODB_AUTH_USERNAME: mongo
      ME_CONFIG_MONGODB_AUTH_PASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: secret
    depends_on:
      - mongo

  cypress:
    image: doanbaanh/cypress:latest
    container_name: cypress
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:cached
      - ./workspace/${DIR}/tests:/e2e:cached
      - ./cache/cypress/config:/root/.config:cached
      - ./cache/cypress/cache:/root/.cache:cached
    working_dir: /e2e
    environment:
      - DISPLAY=${IP}:0
      - BASE_URL=${BASE_URL}
    links:
      - web:${BASE_URL}

  ftp:
    image: bogem/ftp
    container_name: ftp
    volumes:
      - ./workspace/${DIR}:/home/vsftpd:cached
    environment:
      - FTP_USER=${USERNAME}
      - FTP_PASS=${PASSWORD}
      - PASV_ADDRESS=${PASV_ADDRESS}
    ports:
      - 20:20
      - 21:21
      - 47400-47470:47400-47470

volumes:
  cypress-data:
  