version: '2.4'

services:

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    restart: always
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    logging:
      driver: none
