version: '2.4'

services:

  web:
    image: doanbaanh/nginx:1.20
    container_name: web
    restart: always
    volumes:
      - workspace-data:/var/www:cached
    ports:
      - 80:80
      - 443:443
